package modele;

public class Hero {
	public enum CASQUE {CASQUE1, CASQUE2, CASQUE3, CASQUE4, CASQUE5, }
	public enum ARMURE {ARMURE1, ARMURE2, ARMURE3, ARMURE4, ARMURE5, }
	public enum CAPE {CAPE1, CAPE2, CAPE3, CAPE4, CAPE5, }
	public enum BOTTES {BOTTES1, BOTTES2, BOTTES3, BOTTES4, BOTTES5}
	public enum BACKGROUND {BACKGROUND1, BACKGROUND2, BACKGROUND3, BACKGROUND4, BACKGROUND5}
	
	
	
	

}
